use_frameworks!

target 'SyncServer-Shared_Example' do
	pod 'SyncServer-Shared', :path => '../'

	target 'SyncServer-Shared_Tests' do
		inherit! :search_paths
		pod 'SyncServer-Shared', :path => '../'
	end

	# 9/14/17; Cocoapods isn't quite ready for Xcode9. This is a workaround:
	# See also https://github.com/CocoaPods/CocoaPods/issues/6791

	post_install do |installer|

# 		myTargets = ['Gloss']
	
		installer.pods_project.targets.each do |target|
# 			if myTargets.include? target.name
# 				target.build_configurations.each do |config|
# 					config.build_settings['SWIFT_VERSION'] = '3.2'
# 				end
# 			end
			
			if target.name == "SyncServer-Shared"
				target.build_configurations.each do |config|
					config.build_settings['OTHER_SWIFT_FLAGS'] = '-DTESTING'
				end
			end
		end
	end
end
